import type { NextPage } from "next";
import Head from "next/head";
import useSWR from "swr";
import "twin.macro";
import fetcher from "../utils/fetcher";

const Data = () => {
  const { data, error } = useSWR<{ foo: string }>("/api/albums", fetcher);

  if (error) return <p>Failed to load</p>;
  if (!data) return <p>Loading...</p>;

  return <p>Hello {data.foo}!</p>;
};

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Spotify Albums</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <h1 tw="my-5 text-2xl font-bold">Spotify Albums</h1>

      <p>
        Get started by editing <code>pages/index.js</code>
      </p>

      <div tw="my-3">
        <Data />
      </div>
    </main>
  </div>
);

export default Home;
